spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output = true

# This configures Spring Boot to trust and use forwarded headers (like X-Forwarded-For) when behind a proxy or load balancer
server.forward-headers-strategy=framework 

server.port=8080
ADYEN_API_KEY=AQFDhmfxK4zLaRBHw0m/n3Q5qf3VaY9UCJ16aExb1nSuk2NFisZiGclvMiVgB/7xzYuhmDgJK+Gv6oarjCdXBWuGt7+xaBDBXVsNvuR83LVYjEgiTGAH-5uSG8W2i3g/LVEGjY6yziPsKuOKR8LsSAsauwSay1KM=-i1iatc23m8.UxcAV:?c
ADYEN_MERCHANT_ACCOUNT=AdyenPPImplementationTrainingTest_EstuateAtlanta_TEST
ADYEN_CLIENT_KEY=test_I6KN3PCBVZAJNBQOPIT6EZZEQUI2TXGV
ADYEN_HMAC_KEY=584DCF83E70AC7E83A718ACAA4FA36A53AE8F8AC8533308310700A2C0892F715
